let nameList = [
  "Time",
  "Past",
  "Future",
  "Dev",
  "Fly",
  "Flying",
  "Soar",
  "Soaring",
  "Power",
  "Falling",
  "Fall",
  "Jump",
  "Cliff",
  "Mountain",
  "Rend",
  "Red",
  "Blue",
  "Green",
  "Yellow",
  "Gold",
  "Demon",
  "Demonic",
  "Panda",
  "Cat",
  "Kitty",
  "Kitten",
  "Zero",
  "Memory",
  "Trooper",
  "XX",
  "Bandit",
  "Fear",
  "Light",
  "Glow",
  "Tread",
  "Deep",
  "Deeper",
  "Deepest",
  "Mine",
  "Your",
  "Worst",
  "Enemy",
  "Hostile",
  "Force",
  "Video",
  "Game",
  "Donkey",
  "Mule",
  "Colt",
  "Cult",
  "Cultist",
  "Magnum",
  "Gun",
  "Assault",
  "Recon",
  "Trap",
  "Trapper",
  "Redeem",
  "Code",
  "Script",
  "Writer",
  "Near",
  "Close",
  "Open",
  "Cube",
  "Circle",
  "Geo",
  "Genome",
  "Germ",
  "Spaz",
  "Shot",
  "Echo",
  "Beta",
  "Alpha",
  "Gamma",
  "Omega",
  "Seal",
  "Squid",
  "Money",
  "Cash",
  "Lord",
  "King",
  "Duke",
  "Rest",
  "Fire",
  "Flame",
  "Morrow",
  "Break",
  "Breaker",
  "Numb",
  "Ice",
  "Cold",
  "Rotten",
  "Sick",
  "Sickly",
  "Janitor",
  "Camel",
  "Rooster",
  "Sand",
  "Desert",
  "Dessert",
  "Hurdle",
  "Racer",
  "Eraser",
  "Erase",
  "Big",
  "Small",
  "Short",
  "Tall",
  "Sith",
  "Bounty",
  "Hunter",
  "Cracked",
  "Broken",
  "Sad",
  "Happy",
  "Joy",
  "Joyful",
  "Crimson",
  "Destiny",
  "Deceit",
  "Lies",
  "Lie",
  "Honest",
  "Destined",
  "Bloxxer",
  "Hawk",
  "Eagle",
  "Hawker",
  "Walker",
  "Zombie",
  "Sarge",
  "Capt",
  "Captain",
  "Punch",
  "One",
  "Two",
  "Uno",
  "Slice",
  "Slash",
  "Melt",
  "Melted",
  "Melting",
  "Fell",
  "Wolf",
  "Hound",
  "Legacy",
  "Sharp",
  "Dead",
  "Mew",
  "Chuckle",
  "Bubba",
  "Bubble",
  "Sandwich",
  "Smasher",
  "Extreme",
  "Multi",
  "Universe",
  "Ultimate",
  "Death",
  "Ready",
  "Monkey",
  "Elevator",
  "Wrench",
  "Grease",
  "Head",
  "Theme",
  "Grand",
  "Cool",
  "Kid",
  "Boy",
  "Girl",
  "Vortex",
  "Paradox",
];
const comments = [
  "Great job on this project!",
  "I really enjoyed reading your article.",
  "This is fantastic content!",
  "Keep up the good work!",
  "I found this incredibly helpful.",
  "Thanks for sharing!",
  "Awesome!",
  "Well done!",
  "I appreciate your insights.",
  "This made my day!",
  "Fantastic work!",
  "Very informative!",
  "You nailed it!",
  "I'm impressed!",
  "Brilliant!",
  "Outstanding!",
  "You're amazing!",
  "I love your style!",
  "This is gold!",
  "You're a genius!",
  "Impressive!",
  "You've got talent!",
  "You've got my respect!",
  "I'm inspired!",
  "Mind-blowing!",
  "Exceptional!",
  "You're a rockstar!",
  "Incredible!",
  "You're on fire!",
  "Phenomenal!",
  "You've outdone yourself!",
  "Remarkable!",
  "You're a legend!",
  "You're on point!",
  "You're a wizard!",
  "You're a master!",
  "You're a champion!",
  "You're a star!",
  "You're a pro!",
  "You're a hero!",
  "You're unstoppable!",
  "You're a powerhouse!",
  "You're on a roll!",
  "You're a phenomenon!",
  "You're a virtuoso!",
  "You're a maestro!",
  "You're a legend in the making!",
  "You're on top of your game!",
  "You're the best!",
  "You're on another level!",
];

export function generateRandomComment() {
  const randomIndex = Math.floor(Math.random() * comments.length);
  return comments[randomIndex];
}

export function generateName() {
  return nameList[Math.floor(Math.random() * nameList.length)];
}
